version: "2.1"
services:
  openldap:
    image: registry.opensuse.org/opensuse/openldap
    ports:
      - "389:389"
      - "636:636"
    environment:
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_CONFIG_PASSWORD=config
      - LDAP_SEED_LDIF_PATH=/tmp/ldap_seed_ldif
    hostname: openldap.example.org
    volumes:
    #   - ./docker-files/ldapdb:/var/lib/ldap
    #   - ./docker-files/ldapconf:/etc/openldap/slapd.d
      - ./docker-files/openldap/ldap_seed_ldif:/tmp/ldap_seed_ldif
